development:
  APPLICATION_NAME:
  RAILS_ENV:
  RAILS_MAX_THREADS:
  API_PORT:
  API_VERSION:
  DB_NAME:
  DB_HOSTNAME:
  DB_USERNAME:
  DB_PASSWORD:
  DB_PORT:
  ENCRYPTION_KEY:
  FLIPPER_USER:
  FLIPPER_PASSWORD:
  ADMIN_NAME:
  ADMIN_PASSWORD:
test:
  APPLICATION_NAME:
  RAILS_ENV:
  RAILS_MAX_THREADS:
  API_PORT:
  API_VERSION:
  DB_NAME:
  DB_HOSTNAME:
  DB_USERNAME:
  DB_PASSWORD:
  DB_PORT:
  ENCRYPTION_KEY:
