default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  reconnect: true
  encoding: unicode
  port: 9993

development:
  <<: *default
  database: balance-ctrl-enhanced-development
  host: localhost
  username: postgres
  password: postgres

test:
  <<: *default
  database: balance-ctrl-enhanced-test

production:
  <<: *default
  database: balance-ctrl-enhanced-production
