default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  reconnect: true
  encoding: unicode

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") %>
  host: <%= ENV.fetch("DB_HOSTNAME") %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  port: <%= ENV.fetch("DB_PORT") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") %>
  host: <%= ENV.fetch("DB_HOSTNAME") %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  port: <%= ENV.fetch("DB_PORT") %>

production:
  <<: *default
