name: Linters

on: pull_request

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ">=2.7.x"
      - name: Setup Rubocop
        run: |
          gem install --no-document rubocop -v '>= 1.0, < 2.0' # https://docs.rubocop.org/en/stable/installation/
          gem install --no-document rubocop-rails -v '>= 2.0, < 3.0'
          [ -f .rubocop.yml ] || wget https://raw.githubusercontent.com/davidmrtz-dev/balance-ctrl-api/main/.rubocop.yml
      - name: Rubocop Report
        run: rubocop --color
