name: Tests

on: pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports: ['5432:5432']
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          ruby-version: ${{ env.RUBY }}
      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/test
          RAILS_ENV: test
          PG_USER: postgres
        run: |
          bin/rails db:create db:migrate
          bundle exec rspec
