name: Tests

on: pull_request

jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ">=2.7.x"
      - name: Install Dependencies
        run: |
          sudo apt install -yqq libpq-dev
          gem install bundler
      - name: Install Gems
        run: |
          bundle install
      - name: RSpec Report
        run: bundle exec rspec spec --force-color --format documentation
