name: Tests

on:
  pull_request:
    branches:
      - "main"
      - "development"

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4

      - name: Install PostgreSQL 11 client
        run: |
          sudo apt-get -yqq install libpq-dev

      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Build App
        env:
          RAILS_ENV: test
          DB_NAME: balance_ctrl_api_test
          DB_HOSTNAME: localhost
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          DB_PORT: 5432
          ENCRYPTION_KEY: 1e41a9ca2744baecaa49b5b374a276fc
        run: |
          gem install bundler:1.17.2
          bundle install --jobs 4 --retry 3
          rails db:drop db:create db:schema:load
      - name: Build and run tests
        env:
          RAILS_ENV: test
          DB_NAME: balance_ctrl_api_test
          DB_HOSTNAME: localhost
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          DB_PORT: 5432
          ENCRYPTION_KEY: 1e41a9ca2744baecaa49b5b374a276fc
        run: |
          rails db:migrate
          bundle exec rspec
